baseurl = "http://www.kanej.me"
languageCode = "en-us"
theme = "hugo-identity-theme"
title = "Kanej"

googleAnalytics = "UA-21599577-2"

[params]
        favicon = "favicon.png"

        name = "John Kane"
        position = "Programmer"
        email = "john@kanej.me"

        background = "bg3.jpg"
        avatar = "teadrinker.jpg"

[[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "https://twitter.com/john_kane"

[[params.social]]
        title = "Github"
        icon = "fa-github"
        link = "https://github.com/kanej"

[[params.social]]
        title = "Linkedin"
        icon = "fa-linkedin"
        link = "https://www.linkedin.com/in/johnkane84"

[params.footer]
        copyright = "2016 John Kane"
